apiVersion: v1
kind: Template
metadata:
  name: kafka-connect
parameters:
- name: KAFKA_CONNECT_IMAGE
  value: quay.io/cloudservices/xjoin-kafka-connect-strimzi
- name: KAFKA_CONNECT_IMAGE_TAG
  value: c06acd0
- name: BOOTSTRAP_SERVERS
  value: platform-mq-kafka-bootstrap.platform-mq.svc.cluster.local:9093
- name: NUM_REPLICAS
  value: '1'
- name: VERSION
  value: '2.5.0'
- name: CPU_REQUESTS
  value: 500m
- name: CPU_LIMITS
  value: '1'
- name: MEMORY_REQUESTS
  value: 2Gi
- name: MEMORY_LIMITS
  value: 4Gi

objects:
- apiVersion: kafka.strimzi.io/v1beta1
  kind: KafkaConnect
  metadata:
    name: xjoin-kafka-connect-strimzi
    labels:
      app: xjoin-kafka-connect-strimzi
    annotations:
      strimzi.io/use-connector-resources: "true"
  spec:
    image: ${KAFKA_CONNECT_IMAGE}:${KAFKA_CONNECT_IMAGE_TAG}
    version: ${VERSION}
    replicas: ${{NUM_REPLICAS}}
    resources:
      limits:
        cpu: ${CPU_LIMITS}
        memory: ${MEMORY_LIMITS}
      requests:
        cpu: ${CPU_REQUESTS}
        memory: ${MEMORY_REQUESTS}

    bootstrapServers: ${BOOTSTRAP_SERVERS}
    config:
      group.id: xjoin-connect-cluster-strimzi
      offset.storage.topic: connect-cluster-offsets
      config.storage.topic: connect-cluster-configs
      status.storage.topic: connect-cluster-status
    template:
      pod:
        imagePullSecrets:
          - name: quay-cloudservices-pull
          - name: rh-registry-pull

- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: xjoin-kafka-connect-strimzi
    name: xjoin-kafka-connect-strimzi
  spec:
    ports:
    - name: rest-api
      port: 8083
      protocol: TCP
      targetPort: 8083
    - name: prometheus
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: xjoin-kafka-connect-strimzi
    sessionAffinity: None
    type: ClusterIP
