
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: cyndipipelines.cyndi.cloud.redhat.com
spec:
  group: cyndi.cloud.redhat.com
  names:
    kind: CyndiPipeline
    listKind: CyndiPipelineList
    plural: cyndipipelines
    singular: cyndipipeline
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: CyndiPipeline is the Schema for the cyndipipelines API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CyndiPipelineSpec defines the desired state of CyndiPipeline
          properties:
            appName:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            insightsOnly:
              type: boolean
            tasksMax:
              format: int64
              type: integer
          required:
          - appName
          - insightsOnly
          - tasksMax
          type: object
        status:
          description: CyndiPipelineStatus defines the observed state of CyndiPipeline
          properties:
            cyndiConfigVersion:
              type: string
            cyndiPipelineName:
              type: string
            initialSyncInProgress:
              type: boolean
            pipelineVersion:
              type: string
            previousPipelineVersion:
              type: string
            syndicatedDataIsValid:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: boolean
            tableName:
              type: string
            validationDelaySeconds:
              format: int64
              type: integer
            validationFailedCount:
              format: int64
              type: integer
          required:
          - cyndiConfigVersion
          - cyndiPipelineName
          - initialSyncInProgress
          - pipelineVersion
          - previousPipelineVersion
          - syndicatedDataIsValid
          - tableName
          - validationDelaySeconds
          - validationFailedCount
          type: object
      type: object
  version: v1beta1
  versions:
  - name: v1beta1
    served: true
    storage: true
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
